### PR TITLE
fix: search bar event issue

### LINKED ISSUE #278: [BUG] Search does not execute on first click
image
search bar>enter query>click search icon>nothing>click again>works

### PR DESCRIPTION
**Pull request by 2paperstar**
resolve #278

### CODE REVIEW

File: src/app/components/templates/Navbar/SearchBar.tsx [hunk 1]
```diff
@@ -15,139 +15,144 @@ interface SearchBarProps {
...
+                onClick={() => setKeyword('')}
+              >
+                <CloseIcon className="h-4 w-4 stroke-greyDark dark:stroke-dark_white" />
+              </button>
+            </Analytics>
+          )}
+        </div>
+        <>
+          <div className="flex h-full md:hidden">
+            {isExpanded ? (
```
Comment (dohyun-ko) [inline src/app/components/templates/Navbar/SearchBar.tsx:125]: 깔끔해졌다

**Review by dohyun-ko — APPROVED** [review]
GOOD
